# Generated by Django 5.0.6 on 2024-07-07 12:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0002_remove_doctor_speciality_doctor_specialty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
