# Generated by Django 5.0.6 on 2024-07-10 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0007_medicalbill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalBill',
        ),
    ]
